""""jobs+enrichment"

Revision ID: 72b1699ac451
Revises: d891fb5e34cd
Create Date: 2026-05-30 19:10:20.418523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72b1699ac451'
down_revision: Union[str, Sequence[str], None] = 'd891fb5e34cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrichment_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', name='jobstatus'), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrichment_jobs_news_id'), 'enrichment_jobs', ['news_id'], unique=False)
    op.create_index(op.f('ix_enrichment_jobs_status'), 'enrichment_jobs', ['status'], unique=False)
    op.create_table('news_enriched',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categories', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('has_video', sa.Boolean(), nullable=True),
    sa.Column('extra_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enriched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_enriched_news_id'), 'news_enriched', ['news_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_enriched_news_id'), table_name='news_enriched')
    op.drop_table('news_enriched')
    op.drop_index(op.f('ix_enrichment_jobs_status'), table_name='enrichment_jobs')
    op.drop_index(op.f('ix_enrichment_jobs_news_id'), table_name='enrichment_jobs')
    op.drop_table('enrichment_jobs')
    # ### end Alembic commands ###
